#! /bin/sh

setxkbmap -option grp:alt_shift_toggle us,ru &
pgrep -x sxhkd > /dev/null || sxhkd &



#bspc monitor -d I II III IV
#multi monitor

bspc monitor -d 2 3
bspc monitor HDMI-A-O 3 4



xrandr --output HDMI-A-0 --above eDP


bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
